### ISSUE TITLE
The tool is crashed on project opening

### ISSUE THREAD

**Issue by ruaivantso** [thunder-engine/thunderengine.org#2]
System info: Linux iva 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Steps to reproduce: Open previously created project
Expected result: project is opened
Actual result: the tool is crashed

**Comment by eprikazchikov** [comment]
miss board
