### ISSUE TITLE
The tool is crashed on project creating

### ISSUE THREAD

**Issue by ruaivantso** [thunder-engine/thunderengine.org#3]
**System info:** Linux iva 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**Steps to reproduce:** create project
**Expected result:** project is created
**Actual result:** the tool is crashed
**Additional info:** if restart the tool the just created project is displayed on 'welcome' view

**Comment by eprikazchikov** [comment]
miss board
